import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        'ren-object-card': resolve(__dirname, 'src/ren-object-card.ts'),
        'ren-student-card': resolve(__dirname, 'src/ren-student-card.ts'),
        'ren-student-row': resolve(__dirname, 'src/ren-student-row.ts'),
        'ren-student-data-row': resolve(__dirname, 'src/ren-student-data-row.ts'),
        'ren-student-profile': resolve(__dirname, 'src/ren-student-profile.ts'),
        'ren-student-header': resolve(__dirname, 'src/ren-student-header.ts'),
        'ren-student-detail': resolve(__dirname, 'src/ren-student-detail.ts'),
        'ren-class': resolve(__dirname, 'src/ren-class.ts'),
        'ren-assignment': resolve(__dirname, 'src/ren-assignment.ts'),
        'ren-assessment': resolve(__dirname, 'src/ren-assessment.ts'),
        'ren-teacher-card': resolve(__dirname, 'src/ren-teacher-card.ts'),
        'ren-teacher-row': resolve(__dirname, 'src/ren-teacher-row.ts'),
        'ren-teacher-data-row': resolve(__dirname, 'src/ren-teacher-data-row.ts'),
        'ren-teacher-profile': resolve(__dirname, 'src/ren-teacher-profile.ts'),
        'ren-teacher-header': resolve(__dirname, 'src/ren-teacher-header.ts'),
        'ren-class-card': resolve(__dirname, 'src/ren-class-card.ts'),
        'ren-class-row': resolve(__dirname, 'src/ren-class-row.ts'),
        'ren-class-data-row': resolve(__dirname, 'src/ren-class-data-row.ts'),
        'ren-class-profile': resolve(__dirname, 'src/ren-class-profile.ts'),
        'ren-class-header': resolve(__dirname, 'src/ren-class-header.ts'),
        'ren-school-card': resolve(__dirname, 'src/ren-school-card.ts'),
        'ren-school-row': resolve(__dirname, 'src/ren-school-row.ts'),
        'ren-school-data-row': resolve(__dirname, 'src/ren-school-data-row.ts'),
        'ren-school-profile': resolve(__dirname, 'src/ren-school-profile.ts'),
        'ren-school-header': resolve(__dirname, 'src/ren-school-header.ts'),
        'ren-district-card': resolve(__dirname, 'src/ren-district-card.ts'),
        'ren-district-row': resolve(__dirname, 'src/ren-district-row.ts'),
        'ren-district-data-row': resolve(__dirname, 'src/ren-district-data-row.ts'),
        'ren-district-profile': resolve(__dirname, 'src/ren-district-profile.ts'),
        'ren-district-header': resolve(__dirname, 'src/ren-district-header.ts'),
        'ren-assessment-card': resolve(__dirname, 'src/ren-assessment-card.ts'),
        'ren-assessment-row': resolve(__dirname, 'src/ren-assessment-row.ts'),
        'ren-assessment-data-row': resolve(__dirname, 'src/ren-assessment-data-row.ts'),
        'ren-assessment-profile': resolve(__dirname, 'src/ren-assessment-profile.ts'),
        'ren-assessment-header': resolve(__dirname, 'src/ren-assessment-header.ts'),
        'ren-assignment-card': resolve(__dirname, 'src/ren-assignment-card.ts'),
        'ren-assignment-row': resolve(__dirname, 'src/ren-assignment-row.ts'),
        'ren-assignment-profile': resolve(__dirname, 'src/ren-assignment-profile.ts'),
        'ren-assignment-header': resolve(__dirname, 'src/ren-assignment-header.ts'),
        'ren-skill-card': resolve(__dirname, 'src/ren-skill-card.ts'),
        'ren-skill-row': resolve(__dirname, 'src/ren-skill-row.ts'),
        'ren-skill-data-row': resolve(__dirname, 'src/ren-skill-data-row.ts'),
        'ren-skill-profile': resolve(__dirname, 'src/ren-skill-profile.ts'),
        'ren-skill-header': resolve(__dirname, 'src/ren-skill-header.ts'),
        'ren-resource-card': resolve(__dirname, 'src/ren-resource-card.ts'),
        'ren-resource-row': resolve(__dirname, 'src/ren-resource-row.ts'),
        'ren-resource-profile': resolve(__dirname, 'src/ren-resource-profile.ts'),
        'ren-resource-header': resolve(__dirname, 'src/ren-resource-header.ts'),
        'ren-score-card': resolve(__dirname, 'src/ren-score-card.ts'),
        'ren-score-row': resolve(__dirname, 'src/ren-score-row.ts'),
        'ren-score-data-row': resolve(__dirname, 'src/ren-score-data-row.ts'),
        'ren-score-profile': resolve(__dirname, 'src/ren-score-profile.ts'),
        'ren-score-header': resolve(__dirname, 'src/ren-score-header.ts'),
        'ren-standard-card': resolve(__dirname, 'src/ren-standard-card.ts'),
        'ren-standard-row': resolve(__dirname, 'src/ren-standard-row.ts'),
        'ren-standard-profile': resolve(__dirname, 'src/ren-standard-profile.ts'),
        'ren-standard-header': resolve(__dirname, 'src/ren-standard-header.ts'),
        'ren-proficiency-prediction-card': resolve(__dirname, 'src/ren-proficiency-prediction-card.ts'),
        'ren-proficiency-prediction-row': resolve(__dirname, 'src/ren-proficiency-prediction-row.ts'),
        'ren-proficiency-prediction-profile': resolve(__dirname, 'src/ren-proficiency-prediction-profile.ts'),
        'ren-proficiency-prediction-header': resolve(__dirname, 'src/ren-proficiency-prediction-header.ts'),
        'ren-insight-card': resolve(__dirname, 'src/ren-insight-card.ts'),
        'ren-insight-row': resolve(__dirname, 'src/ren-insight-row.ts'),
        'ren-insight-profile': resolve(__dirname, 'src/ren-insight-profile.ts'),
        'ren-insight-header': resolve(__dirname, 'src/ren-insight-header.ts'),
        'ren-solution-card': resolve(__dirname, 'src/ren-solution-card.ts'),
        'ren-solution-row': resolve(__dirname, 'src/ren-solution-row.ts'),
        'ren-solution-profile': resolve(__dirname, 'src/ren-solution-profile.ts'),
        'ren-solution-header': resolve(__dirname, 'src/ren-solution-header.ts'),
        'ren-product-assignment-card': resolve(__dirname, 'src/ren-product-assignment-card.ts'),
        'ren-product-assignment-row': resolve(__dirname, 'src/ren-product-assignment-row.ts'),
        'ren-product-assignment-profile': resolve(__dirname, 'src/ren-product-assignment-profile.ts'),
        'ren-product-assignment-header': resolve(__dirname, 'src/ren-product-assignment-header.ts'),
        'ren-product-card': resolve(__dirname, 'src/ren-product-card.ts'),
        'ren-product-row': resolve(__dirname, 'src/ren-product-row.ts'),
        'ren-product-profile': resolve(__dirname, 'src/ren-product-profile.ts'),
        'ren-product-header': resolve(__dirname, 'src/ren-product-header.ts'),
        'ren-activity-event-card': resolve(__dirname, 'src/ren-activity-event-card.ts'),
        'ren-activity-event-row': resolve(__dirname, 'src/ren-activity-event-row.ts'),
        'ren-activity-event-profile': resolve(__dirname, 'src/ren-activity-event-profile.ts'),
        'ren-activity-event-header': resolve(__dirname, 'src/ren-activity-event-header.ts'),
        'ren-activity-card': resolve(__dirname, 'src/ren-activity-card.ts'),
        'ren-activity-row': resolve(__dirname, 'src/ren-activity-row.ts'),
        'ren-activity-profile': resolve(__dirname, 'src/ren-activity-profile.ts'),
        'ren-activity-header': resolve(__dirname, 'src/ren-activity-header.ts'),
        'ren-lesson-card': resolve(__dirname, 'src/ren-lesson-card.ts'),
        'ren-lesson-row': resolve(__dirname, 'src/ren-lesson-row.ts'),
        'ren-lesson-profile': resolve(__dirname, 'src/ren-lesson-profile.ts'),
        'ren-lesson-header': resolve(__dirname, 'src/ren-lesson-header.ts'),
        'ren-live-session-card': resolve(__dirname, 'src/ren-live-session-card.ts'),
        'ren-live-session-row': resolve(__dirname, 'src/ren-live-session-row.ts'),
        'ren-live-session-profile': resolve(__dirname, 'src/ren-live-session-profile.ts'),
        'ren-live-session-header': resolve(__dirname, 'src/ren-live-session-header.ts'),
        'ren-report-card': resolve(__dirname, 'src/ren-report-card.ts'),
        'ren-report-row': resolve(__dirname, 'src/ren-report-row.ts'),
        'ren-report-profile': resolve(__dirname, 'src/ren-report-profile.ts'),
        'ren-report-header': resolve(__dirname, 'src/ren-report-header.ts'),
        'ren-educator-academy-module-card': resolve(__dirname, 'src/ren-educator-academy-module-card.ts'),
        'ren-educator-academy-module-row': resolve(__dirname, 'src/ren-educator-academy-module-row.ts'),
        'ren-educator-academy-module-profile': resolve(__dirname, 'src/ren-educator-academy-module-profile.ts'),
        'ren-onboarding-step-card': resolve(__dirname, 'src/ren-onboarding-step-card.ts'),
        'ren-onboarding-step-row': resolve(__dirname, 'src/ren-onboarding-step-row.ts'),
        'ren-onboarding-step-profile': resolve(__dirname, 'src/ren-onboarding-step-profile.ts'),
        'ren-onboarding-checklist-card': resolve(__dirname, 'src/ren-onboarding-checklist-card.ts'),
        'ren-onboarding-checklist-row': resolve(__dirname, 'src/ren-onboarding-checklist-row.ts'),
        'ren-onboarding-checklist-profile': resolve(__dirname, 'src/ren-onboarding-checklist-profile.ts'),
        'ren-student-group-card': resolve(__dirname, 'src/ren-student-group-card.ts'),
        'ren-student-group-row': resolve(__dirname, 'src/ren-student-group-row.ts'),
        'ren-student-group-profile': resolve(__dirname, 'src/ren-student-group-profile.ts'),
        'ren-learning-path-card': resolve(__dirname, 'src/ren-learning-path-card.ts'),
        'ren-learning-path-row': resolve(__dirname, 'src/ren-learning-path-row.ts'),
        'ren-learning-path-profile': resolve(__dirname, 'src/ren-learning-path-profile.ts'),
      },
      formats: ['es'],
    },
    rollupOptions: {
      external: ['lit', 'lit/decorators.js', /^lit\//],
    },
    outDir: 'dist',
    emptyOutDir: true,
  },
});
